apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitor-sa
  labels:
    app: alertmanager 
spec:
  ports:     
    - port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: alertmanager
  type: NodePort
